name: watermark
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - arxiv
    - PyMuPDF
    - Pillow
    - pytesseract
    - numpy
    - tqdm
    - anthropic
    - python-dotenv